id: http://example.org/dh-stepper-example
name: dh-stepper-example
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  View:
    abstract: true
    slots:
      - id
      - name
      - type
  Common:
    is_a: View
    slots: 
      - common_field
  A:
    is_a: View
    slots:
      - A1
      - A2
      - A3
  B:
    is_a: View
    slots:
      - B1
      - B2
      - B3
  C:
    is_a: View
    slots:
      - C1
      - C2
      - C3
      
slots:
  id:
    identifier: true
    slot_group: Basic info
    rank: 1
  name:
    required: true
    slot_group: Basic info
    rank: 2
  type:
    required: true
    multivalued: true
    range: TypeOptions
    slot_group: Basic info
    rank: 3
  common_field:
    slot_group: Basic info
    rank: 4
  A1:
    slot_group: A
    rank: 5
  A2:
    slot_group: A
    rank: 6
  A3:
    slot_group: A
    rank: 7
  B1:
    slot_group: B
    rank: 5
  B2:
    slot_group: B
    rank: 6
  B3:
    slot_group: B
    rank: 7
  C1:
    slot_group: C
    rank: 5
  C2:
    slot_group: C
    rank: 6
  C3:
    slot_group: C
    rank: 7

  # this allows DH to order slot groups
  Basic info:
    rank: 1
  A:
    rank: 2
  B:
    rank: 2
  C:
    rank: 2

enums:
  TypeOptions:
    permissible_values:
      - A:
      - B:
      - C:

# TODO: open DH issue that these shouldn't be required
types:
  phony: