id: http://example.org/dh-stepper-example
name: dh-stepper-example
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  View:
    abstract: true
    slots:
      - id
      - name
      - type
  Soil:
    is_a: View
    slots: 
      - depth
  MetaT:
    is_a: View
    slots:
      - T1
      - T2
      - T3
  MetaG:
    is_a: View
    slots:
      - G1
      - G2
      - G3
  MetaP:
    is_a: View
    slots:
      - P1
      - P2
      - P3
      
slots:
  id:
    identifier: true
    slot_group: Sample info
    rank: 1
  name:
    required: true
    slot_group: Sample info
    rank: 2
  type:
    required: true
    multivalued: true
    range: TypeOptions
    slot_group: Sample info
    rank: 3
  depth:
    slot_group: Sample info
    rank: 4
  T1:
    slot_group: MetaT
    rank: 5
    required: true
  T2:
    slot_group: MetaT
    rank: 6
    required: true
  T3:
    slot_group: MetaT
    rank: 7
    required: true
  G1:
    slot_group: MetaG
    rank: 5
    required: true
  G2:
    slot_group: MetaG
    rank: 6
    required: true
  G3:
    slot_group: MetaG
    rank: 7
    required: true
  P1:
    slot_group: MetaP
    rank: 5
    required: true
  P2:
    slot_group: MetaP
    rank: 6
    required: true
  P3:
    slot_group: MetaP
    rank: 7
    required: true

  # this allows DH to order slot groups
  Sample info:
    rank: 1
  MetaT:
    rank: 2
  MetaG:
    rank: 2
  MetaP:
    rank: 2

enums:
  TypeOptions:
    permissible_values:
      - MetaT:
      - MetaG:
      - MetaP:

# TODO: open DH issue that these shouldn't be required
types:
  phony: